config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks do
    get 'bookmarks/index' => :index, as: 'bookmarks'
  end

  get 'searches/index'

  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    get "bookmarks/toggle"
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_feed.html.haml
- if @feed_items.any?
  %ol.posts
    = render @feed_items
  = will_paginate @feed_items

app/views/shared/_post_form.html.haml
= form_for(@post, html: { multipart: true }) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_area :content, placeholder: "What's up??"
  = f.submit "Post", class: "btn btn-primary"
  %span.picture
    = f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'
:javascript
  $('#post_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });

app/views/shared/_stats.html.haml
- @user ||= current_user
.stats
  %a{href: following_user_path(@user)}
    %strong#following.stat
      = @user.following.count
    following
  %a{href: followers_user_path(@user)}
    %strong#followers.stat
      = @user.followers.count
    followers

app/views/shared/_user_info.html.haml
= link_to gravatar_for(current_user, size: 50), current_user
%h1= current_user.name
%span= link_to "view my profile", current_user
%span= link_to "bookmarks", bookmarks_path
%span= pluralize(current_user.posts.count, "post")