config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks do
    get 'bookmarks/index' => :index, as: 'bookmarks'
  end

  get 'searches/index'

  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    get "bookmarks/toggle"
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    Mayopad
  %nav
    %ul
      %li= link_to "Home",   root_path
      %li= link_to "About", about_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "mayopad", root_path, id: "logo"
    - if logged_in?
      .search
        = form_tag searches_index_path, method: :get do
          .text_field
            = text_field_tag(:q)
          .submit
            = submit_tag("Search")
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Home", root_path
        %li= link_to "About", about_path
        - if logged_in?
          - if current_user.admin?
            %li= link_to "Users", users_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Account
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Profile", current_user
              %li= link_to "Settings", edit_user_path(current_user)
              %li.divider
              %li
                = link_to "Log out", logout_path, method: "delete"
        - else
          %li= link_to "Log in", login_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", media: "all", |
      "data-turbolinks-track" => true                  |
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        %div{class: "alert alert-#{message_type}"}= message
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?